# Generated by Django 4.2.3 on 2023-07-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_contract', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300, null=True)),
                ('name_of_the_company_manager', models.CharField(max_length=300)),
                ('date_of_contract', models.DateField()),
                ('contract_number', models.IntegerField()),
                ('nationalid', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=300)),
                ('contract_price', models.IntegerField()),
                ('change', models.BooleanField(default=True)),
                ('update', models.DateField(auto_now=True)),
                ('date_of_cash_deposit', models.DateField()),
                ('cash_deposit_amount', models.BigIntegerField()),
                ('contract_type', models.CharField(max_length=300)),
                ('overdue_account', models.IntegerField(blank=True, null=True)),
                ('company_address', models.CharField(max_length=300)),
                ('marketer', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('printing_cost', models.IntegerField()),
                ('print_account_balance', models.IntegerField()),
                ('print_the_deposited_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField()),
                ('check_in_check_out', models.IntegerField()),
                ('check_registration', models.IntegerField()),
                ('change', models.BooleanField(default=True)),
                ('update', models.DateField(auto_now=True)),
                ('the_row_number', models.IntegerField()),
                ('date_received', models.DateField()),
                ('name_of_assignor', models.CharField(max_length=300)),
                ('registered_check', models.IntegerField()),
                ('bank_name', models.CharField(max_length=300)),
                ('branch_name', models.CharField(max_length=300)),
                ('check_number', models.IntegerField()),
                ('check_amount', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('pay_to', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('check_and_out', models.CharField(max_length=300)),
                ('phone_number_of_the_owner_of_the_check', models.IntegerField()),
                ('national_code', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=300)),
                ('overdue_account', models.IntegerField(blank=True, null=True)),
                ('check_amount', models.IntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_update', to='home.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_update', to='home.product')),
            ],
        ),
    ]
