# Generated by Django 4.2.2 on 2023-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_create_page_delete_edit_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_of_contract',
            field=models.DateTimeField(),
        ),
    ]
