# Generated by Django 4.2.2 on 2023-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_invoice_date_of_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_price', models.IntegerField()),
                ('cash_deposit_amount', models.IntegerField()),
                ('overdue_account', models.IntegerField()),
            ],
        ),
    ]
