# Generated by Django 4.2.2 on 2023-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_invoice_mobile_alter_invoice_nationalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
