# Generated by Django 4.2.2 on 2023-07-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_invoice_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
