# Generated by Django 4.2.2 on 2023-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='overdue_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
