# Generated by Django 4.2.3 on 2023-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_invoice_overdue_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_of_contract',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
