# Generated by Django 4.2.2 on 2023-07-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_invoice_date_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_of_contract',
            field=models.DateField(),
        ),
    ]
