# Generated by Django 4.2.2 on 2023-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_invoice_date_of_cash_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_of_cash_deposit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_of_contract',
            field=models.CharField(max_length=20),
        ),
    ]
