# Generated by Django 4.2.1 on 2023-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_invoice_date_of_cash_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_of_cash_deposit',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_of_contract',
            field=models.DateField(max_length=20),
        ),
    ]
