# Generated by Django 4.2.3 on 2023-07-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_invoice_change_alter_invoice_date_of_cash_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('contract_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_update', to='home.variants'),
        ),
    ]
