# Generated by Django 4.2.3 on 2023-07-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_variants_chart_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='update',
            new_name='date_of_cash_deposit',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='contract_price',
            new_name='overdue_account',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='update',
            new_name='date_of_cash_deposit',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='contract_price',
            new_name='overdue_account',
        ),
        migrations.AlterField(
            model_name='chart',
            name='Invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_overdue_account', to='home.invoice'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_overdue_account', to='home.variants'),
        ),
    ]
