# Generated by Django 4.2.3 on 2023-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_chart_variant_chart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variants',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='due_date',
            field=models.DateField(),
        ),
    ]
