# Generated by Django 4.2.3 on 2023-07-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_variants_alter_product_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_cash_deposit', models.DateTimeField(auto_now=True)),
                ('overdue_account', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Product',
        ),
        migrations.AddField(
            model_name='chart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_overdue_account', to='home.variants'),
        ),
    ]
