# Generated by Django 4.2.3 on 2023-07-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_chart_variant_chart_product_delete_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='Product',
        ),
    ]
