# Generated by Django 4.2.3 on 2023-07-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_chart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
