# Generated by Django 4.2.3 on 2023-07-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_update', to='home.invoice'),
        ),
        migrations.AddField(
            model_name='chart',
            name='overdue_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='check_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_update', to='home.product'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='check_amount',
            field=models.IntegerField(),
        ),
    ]
